### PR TITLE
fix: add ability to pass query params to Get() dns resources and records

### LINKED ISSUE #89: Query params for DNSResources Get()
Hello. Currently, the `Get()` method for [DNSResources](https://github.com/canonical/gomaasclient/blob/master/client/dns_resources.go) does not accept any query params but the [MAAS API docs](https://maas.io/docs/api) show that it should.

We want the ability to pass in query params (specifically `all: bool`) to retrieve the list of `entity.DNSResourceRecords` associated with each Resource. We've temporarily switched to using a forked repo with the desired changes, let me know if you would like me to open a PR with said changes.

This is similar to #67

### PR DESCRIPTION
**Pull request by arturshadnik**
- Updating the `DNSResources` and `DNSResourceRecords` Get() apis to accept query params as specified in the [API docs](https://maas.io/docs/api).

Resolves GH: #89

### CODE REVIEW

**Comment by arturshadnik** [comment]
> Hey! arturshadnik has not signed the Canonical CLA which is required to get this contribution merged on this project.
> Please head over to https://ubuntu.com/legal/contributors to read more about it.

Not sure why the check failed, I signed the CLA earlier today. I've resigned it just in case.

**Comment by troyanov** [comment]
Hi @arturshadnik and thanks for the contribution!

It could be that something is not being properly updated on our side. I will check if there are any issues with the CLA check functionality (could be a stale cache).

**Comment by skatsaounis** [comment]
Hi @arturshadnik 

As you can observe, the issue with cla-check is gone. However, it seems that you need to align the fields inside the structs.

You can try with something like this [snippet](https://gist.github.com/up1/69a6749df9464f15743dbb1a0c711762).

File: entity/dns_resource.go [hunk 1]
```diff
@@ -16,3 +16,10 @@ type DNSResourceParams struct {
 	IPAddresses string `url:"ip_addresses,omitempty"`
 	AddressTTL  int    `url:"address_ttl"`
 }
+
+type DNSResourcesParams struct {
+	All    bool   `url:"all,omitempty"`
```
Comment (skatsaounis) [inline entity/dns_resource.go:21]: https://github.com/canonical/maas/blob/master/src/maasserver/api/dnsresources.py#L155 based on MAAS code, `fqdn` is also a valid parameter. Could you please add it? In addition, if you are up for a MAAS contribution, you can try to open an MP to include it at the pydoc above. It will then be reflected to our API documentation.

**Review by skatsaounis — APPROVED** [review]
LGTM +1 :rocket:
